### ISSUE TITLE
После отправки домашки дата комментария показывает время в другом часовом поясе

### ISSUE THREAD

**Issue by drakulavich** [tough-dev-school/education-backend#1322]
Часовой пояс UTC+4. Сразу после отправки домашки показывает время (час назад):
<img width="281" alt="image" src="https://user-images.githubusercontent.com/129260/200886669-d17a48e9-2cec-4c66-bf43-1934134cbd09.png">

**Comment by nkiryanov** [comment]
Это должны были исправить вот тут #1338 + поддержка на стороне фронта тоже
