### ISSUE TITLE
Соглашение о вызове сервисов

### ISSUE THREAD

**Issue by alevgenk** [tough-dev-school/education-backend#2044]
Здравствуйте!

Подскажите, а какие у вас соглашения в проекте по использованию сервисов?
Ряд сервисов вызываются из вьюшек, форм и т.п., а некоторые другие сервисы - через методы моделей.
Каких правил вы тут придерживаетесь?

**Comment by f213** [comment]
- Мы стараемся вообще не писать код в модели
- Сервисы не должны вызывать другие сервисы
- Один сервис — это один пользовательский сценарий, который можно выразить на человеческом языке. «Принять ответ на домашку» — сценарий, а «перестроить кеш домашек» — это уже не сервис.

От всех этих правил можно отступать в угоду здравому смыслу

**Comment by f213** [comment]
> Уточните про цитируемый фрагмент - не вызывать как, синхронно?

Лучше бы вообще никак не вызывать.

Замечу, что абстрактные рассуждения в таком вопросе много не стоят — лучше присылайте код и мы его обсудим :-)
