### ISSUE TITLE
Проблемы с установкой проекта

### ISSUE THREAD

**Issue by scoutrul** [tough-dev-school/education-backend#2291]
Всем привет! Я заинтересовался вашим проектом, так как имею запрос на создание образовательной платформы, и решил посмотреть как он работает, но при установке докера возникает ошибка связанная с авторизацией и GIT_TOKEN. 

Подскажите пожалуйста подробнее, как это работает?

**Comment by scoutrul** [comment]
я сталкиваюсь с ошибкой при

docker compose up -d
[+] Running 0/4
 - redis Error                                                                                                           0.9s 
 - s3 Error                                                                                                              0.9s 
 - notion-middleware Error                                                                                               0.9s 
 - postgres Error                                                                                                        0.9s 
Error response from daemon: Head "https://ghcr.io/v2/tough-dev-school/notion-middleware/manifests/latest": unauthorized

**Comment by scoutrul** [comment]
Спасибо за фикс!

Подскажите пожалуйста как решить эту проблему с poetry install

![image](https://github.com/tough-dev-school/education-backend/assets/11922258/c187146a-70fb-471b-86b5-36c01a90d022)

**Comment by f213** [comment]
Поправил ридми, спасибо!
