### ISSUE TITLE
Один таск для запуска всех триггеров

### ISSUE THREAD

**Issue by grepto** [tough-dev-school/education-backend#24]
Было бы клёво сделать один таск, который запускает все триггеры, а не лазить каждый раз в settings.py.

Для начала делаем реестр триггеров. Можно через `BaseTrigger.__subclasses__()`, но лучше через фабрику и регистрацию, как [тут](https://github.com/f213/pmdaily-backend/blob/master/src/shipping/shipments/course.py#L18). Важно — чтобы реестр работал, все файлы с триггерами обязательно должны импортироваться в момент запуска приложения.

Затем у к каждого триггера делаем метод класса, который сам себя запускает, аналог того, [что у нас сейчас в тасках](https://github.com/f213/pmdaily-backend/blob/master/src/triggers/tasks.py#L19). Только запускать нужно не сам триггер, а специальную таску, на вход которой мы даём название триггера и заказ, относительно которого мы его инициируем. Это нужно на случай, если какой-нибудь триггер упадёт — поскольку он будет работать в отдельной таске, он не сломает код, и остальные триггеры сработают.

**Comment by f213** [comment]
Триггерных писем у нас больше нет, выносим их на отдельную платформу
