### ISSUE TITLE
Добавить сохранение результатов тестов в CI

### ISSUE THREAD

**Issue by f213** [tough-dev-school/education-backend#304]
<img width="1527" alt="Screenshot 2021-05-05 at 00 07 46" src="https://user-images.githubusercontent.com/1592663/117070055-ed3cf880-ad35-11eb-98ad-aaa4a56c33a9.png">

Нужно прочитать вот [эту доку](https://circleci.com/docs/2.0/collect-test-data/) и сделать, что там говорят

**Comment by Abdujabbar** [comment]
@f213  а этот issue актуален? Можно возьму на работу?

**Comment by f213** [comment]
Да, актуален. Правда мы сейчас используем GitHub actions, и отчёт о тестах нужно делать их средствами, типа [этого](https://github.com/marketplace/actions/publish-test-results).

Какими конкретно — порекомендовать не могу, к сожалению

**Comment by Abdujabbar** [comment]
Ок, давай я попробую изучить тему.
