### ISSUE TITLE
Массовые операции над промокодами

### ISSUE THREAD

**Issue by f213** [tough-dev-school/education-backend#382]
Всякий раз перед запуском нового курса приходится обходить старые промокоды и отключать их. Хочу массовую операцию, в админке. чтобы я просто выбрал их все и отключил.

**Comment by Taranovskiy** [comment]
@f213 , у меня нет прав на контрибьюшн в этот репо:
<img width="1089" alt="image" src="https://user-images.githubusercontent.com/22897018/163064474-3d57ec36-e273-416c-ad6a-98bde3ea48a8.png">

**Comment by f213** [comment]
Выслал тебе инвайт. По-идее, как только ты его примешь, права появятся.

А вообще можно сделать ПР в любой репозиторий, к которому у тебя нет прав, если сделать его форк — тогда в гитхабе появится кнопочка «сделать ПР из мастера моего форка».
