### ISSUE TITLE
Добавить constraint, при котором у Order может быть только один Product

### ISSUE THREAD

**Issue by f213** [tough-dev-school/education-backend#655]
Заказ может иметь несколько разныз [ForeignKey](https://github.com/tough-dev-school/education-backend/blob/master/src/orders/models/order.py#L47) до разных айтемов — курсов, бандлов, записей. При этом по бизнес-логике такой айтем может быть только один. Получается, что у нас есть возможность записать в базу данные, которые нарушат бизнес-логику.

Чтобы этого не было, надо добавить констрейнт, при котором у заказа может быть либо course, либо record, либо bundle, либо course.

**Comment by Abdujabbar** [comment]
А я правильно понял, что это будет [CheckConstraint](https://docs.djangoproject.com/en/3.2/ref/models/options/#django.db.models.Options.constraints) с несколько чеками запросов?  

я не особо глубоко знаком этой темой по этому пытаюсь уточнить

**Comment by f213** [comment]
Да, кажется это самый лучший вариант
