### ISSUE TITLE
Mailchimp → Dashamail

### ISSUE THREAD

**Issue by f213** [tough-dev-school/education-backend#853]
Мейлчимп нас заканселил, поэтому мы мигрируем на dashamail. План миграции:

- [x] Перенести базу подписчиков
- [x] Избавиться от всех упоминаний мейлчимпа:
  - [Автоподписка](https://github.com/tough-dev-school/education-backend/blob/master/src/users/services/user_creator.py#L57) всех новых юзеров
  - [Подписка на цепочки при покупке курса](https://github.com/tough-dev-school/education-backend/blob/master/src/studying/shipment/course.py#L39)
  - Проверить, где ещё встречается
- [x] Сделать подписку новых юзеров, пока просто сабмитить всех юзеров в дашу, как было с мейлчимпом
- [x] Сделать #854 
- [x] Перелить в дашу всех подписчиков, созданных после 15 марта (когда нам заблочили мейлчимп)

За доступами — ко мне в личку

**Comment by da-maltsev** [comment]
Кажется, что все сделано. Задача в [BC](https://3.basecamp.com/5104612/buckets/29069198/todos/6319981726)
