### ISSUE TITLE
Теги для dashamail

### ISSUE THREAD

**Issue by f213** [tough-dev-school/education-backend#854]
Сейчас у нас есть теги для мейлчимпа, но работают они плохо, глючат. Надо сделать вот такую систему:
- [x] Если пользователь интересовался каким-нибудь курсом (то есть создан в момент создания заказа), нужно добавлять ему теги `{source-slug}` и `{productgroup-slug}`. У [группы продуктов](https://github.com/tough-dev-school/education-backend/blob/master/src/products/models/group.py) слага сейчас нет, нужно добавить.
- [x] Если юзер купил курс — нужно добавлять ему тег `{course-slug}-purchased`

После реализации всех тегов нужно обновить их у текущих подписчиков в базе.

**Comment by TvojaMamaLama** [comment]
Что такое {source-slug}?

**Comment by f213** [comment]
Я имел ввиду `course-slug` :-)
