### ISSUE TITLE
Админка заказов: выводить поле desired_bank, фильтровать по нему

### ISSUE THREAD

**Issue by f213** [tough-dev-school/education-backend#861]
У нас появилось уже целых [три банка](https://github.com/tough-dev-school/education-backend/blob/master/src/banking/selector.py#L10). Надо, чтобы в [админке заказов](https://app.tough-dev.school/admin/orders/order/) можно было отфильтровать по ним, а при заходе в заказ — посмотреть, какой там был банк.

**Comment by igoose1** [comment]
@f213, роботизированной строки вроде "tinkoff_bank" и "tinkoff_credit" достаточно или ожидается, что название банка будет более человеческое ("Tinkoff Bank", "Tinkoff Credit")?

**Comment by f213** [comment]
Достаточно роботизированной

**Comment by f213** [comment]
Закрыто в #875.
