### ISSUE TITLE
В админке во всех названиях курса выводить название потока

### ISSUE THREAD

**Issue by f213** [tough-dev-school/education-backend#883]
Сейчас совершенно непонятно, к какому потоку принадлежит курс — приходится догадываться по старшинству. Надо, чтобы вот тут (см. ниже) выводилось название ProductGroup, к которому привязан курс.

<img width="1511" alt="Screenshot 2022-06-20 at 10 55 18" src="https://user-images.githubusercontent.com/1592663/174552950-bf6ee7e8-6ba7-43f7-af90-5ba2fededfd7.png">

**Comment by Taranovskiy** [comment]
@f213 , взял это

**Comment by da-maltsev** [comment]
Судя по всему, это было сделано тут https://github.com/tough-dev-school/education-backend/pull/1502
